version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:30"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: org.hibernate:hibernate-*
    versions:
    - ">= 0"
  - dependency-name: org.springframework.data:spring-data-jpa
    versions:
    - ">= 0"
  - dependency-name: org.springframework:spring-*
    versions:
    - ">= 0"
