language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
os:
- linux
branches:
  only:
  - dev
  - coverity_scan
after_success:
- mvn jacoco:report coveralls:report
env:
  global:
    secure: OdEsm8Nx2o0To3pU5RbNH9xTUbLRncCw22K4NqTN6V1E9Vhl5sQIRru6nzOFaI2ehAKWEJLTC1CnH0wk7QWxXWTKAqpsaVXeJ9SOLqT/U6XCeBdzR2QTVd0i8z86XY/BXBzKXVQMyGcj+no0zDkxwrqzXqAv+pTKST4vEDbPYvc=
sudo: false
addons:
  coverity_scan:
    project:
      name: dannil/HttpDownloader
      description: Build submitted via Travis CI
    notification_email: daniel.nilsson94@outlook.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
