language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

os:
  - linux

branches:
  only:
    - coverity_scan

after_success:
  - mvn jacoco:report coveralls:report
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
  - secure: "PitCLB7YkreA8up5Qy6zq+Y5rRxQeTgwcytGK7gyEV+ZW3PQBzubRrIWX0ef3vVbwI6EQakSYOthj7l5vihOv9/nVI1McAeIf1LZkTDM257zlZysRLywfjKaodM4FaWEcnyeP4Oxbn7bdsZHEF4+i0PkHCxkvVt7pdhJteLbn2A="

addons:
  coverity_scan:
    project:
      name: "dannil/HttpDownloader"
      description: "Build submitted via Travis CI"
    notification_email: bobkant-fyrsvamp@hotmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan