language: java
os: linux
dist: xenial
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
git:
  depth: 99999
branches:
  except:
  - gh-pages
env:
  global:
  - secure: YVLbSjUB/aRhBP/2rPH6b2S2Al/9N/9TY+QGZfaGx8ekbU+4EW6FYS+3hRny7uG4Ut6aPpSspgQF9i5FuYME0z15nDnBEMUMlcy1FTYxn2oJzuX4A2yTuo9aZBB6kH8L9L/uZpnfXb/Uw/8QXEEd1KIV4kPNAfTK2MHF/kdjSPY=
  - secure: BkRSb+4BM7LSFqT/TD1KfxeJwuoU82TaVBZsmXUOnvxCJY9Q9MosLyTmExGG5L2i4MCpE4GjnK5p9r2xAaSBP5W5obbG2SjEVIfL9ylUWF/JE36B+nb7yYy33wFYpmoB6Dj23VSpaWmxP4168ro9dUhdJLe0YIwsQYGTs3zXQnQ=
  - secure: NpYDb7PZOWemneZEr75eHWDCSHAmGy3O77ilRKBHkVhhgLDEhPsSjZJIiilkUJqSfOJIZyu5BDKVF+ePz6tqNBJSlRn5rVYE2DfPUYY5RxRnkU3MXclPzoc+mwNY3vKQWTBP3ipYGe+jb9R38k7GtLdq7yw/AWCxR8nmruyJTfk=
install:
- true
script:
- mvn install -Dmaven.javadoc.skip=true -B -V
# SonarCloud scanner needs to be run with at least Java 11; also make sure we are on the correct branch
after_success:
- if [[ $TRAVIS_JDK_VERSION == openjdk11 && $TRAVIS_BRANCH == dev ]]; then
    mvn sonar:sonar -Dsonar.organization=dannil-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARQUBE_TOKEN;
  fi;

