version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    ignored_updates:
      - match:
          # Should be upgraded all at once in a single PR; not yet possible 
          # with Dependabot so let's handle that manually
          dependency_name: "org.springframework:spring-*"
      - match:
          # Should be upgraded together with core Spring Framework
          dependency_name: "org.springframework.data:spring-data-jpa"
      - match:
          # Should be upgraded all at once in a single PR; not yet possible 
          # with Dependabot so let's handle that manually
          dependency_name: "org.hibernate:hibernate-*"