name: CI

on: push

jobs:
  build:
    strategy:
      matrix:
        java: [17]
      fail-fast: false
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn install -B -V
